# Generated by Django 6.0.2 on 2026-03-17 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tricycle',
            fields=[
                ('body_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('toda_branch', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FareMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='e.g., 35.00', max_digits=6)),
                ('base_distance_km', models.FloatField(default=1.0)),
                ('succeeding_km_rate', models.DecimalField(decimal_places=2, help_text='e.g., 15.00', max_digits=6)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='e.g., 0.20 for 20%', max_digits=4)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trip_mode', models.CharField(choices=[('Direct', 'Direct'), ('Special', 'Special')], default='Direct', max_length=10)),
                ('origin_address', models.CharField(default='Unknown Location', max_length=255)),
                ('destination_address', models.CharField(default='Unknown Destination', max_length=255)),
                ('total_distance_km', models.FloatField()),
                ('stopovers_count', models.IntegerField(default=0)),
                ('computed_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_fare_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('polyline_hash', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fare_matrix', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.farematrix')),
                ('tricycle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.tricycle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('Overcharging', 'Overcharging'), ('Refusal', 'Refusal to Convey'), ('Detour', 'Unnecessary Detour'), ('Arrogance', 'Arrogant Driver')], max_length=20)),
                ('passenger_comments', models.TextField()),
                ('evidence_photo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Investigating', 'Under Investigation'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=15)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.trip')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_provider', models.CharField(choices=[('Local', 'Local (Email/Password)'), ('Google', 'Google OAuth')], default='Local', max_length=10)),
                ('user_type', models.CharField(choices=[('Regular', 'Regular'), ('Student', 'Student'), ('Senior', 'Senior Citizen'), ('PWD', 'Person with Disability')], default='Regular', max_length=10)),
                ('id_photo_url', models.URLField(blank=True, help_text='Link to uploaded CCA ID or PWD ID', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Checked by Admin to approve discount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
