# Generated by Django 6.0.2 on 2026-03-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='manual_body_number',
            field=models.CharField(blank=True, help_text='Used when trip is not linked to the app', max_length=10, null=True),
        ),
    ]
