# Generated by Django 6.0.2 on 2026-04-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_report_manual_body_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farematrix',
            options={'verbose_name': 'Tricycle Fare Ordinance', 'verbose_name_plural': 'Tricycle Fare Ordinances'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='admin_remarks',
        ),
        migrations.RemoveField(
            model_name='report',
            name='evidence_photo_url',
        ),
        migrations.AddField(
            model_name='report',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Official PTRO resolution sent back to the commuter.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='passenger_comments',
            field=models.TextField(blank=True, help_text='The complaint details from the commuter.', null=True),
        ),
    ]
