# Generated by Django 6.0.2 on 2026-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_farematrix_options_remove_report_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tricycle',
            name='driver_name',
            field=models.CharField(blank=True, default='Unknown Driver', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tricycle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tricycle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Unverified', 'Unverified (Colorum/Pending)')], default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='tricycle',
            name='toda_branch',
            field=models.CharField(blank=True, default='Unknown TODA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_photo_url',
            field=models.URLField(blank=True, help_text='Link to uploaded Student ID, Senior Citizen ID, or PWD ID', null=True),
        ),
    ]
