# Generated by Django 6.0.2 on 2026-04-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tricycle_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence_photo_url',
            field=models.URLField(blank=True, help_text='Link to evidence photo', null=True),
        ),
    ]
