# Generated by Django 6.0.2 on 2026-04-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_report_evidence_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='evidence_photo_url',
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_photo',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_photos/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='violation_type',
            field=models.CharField(choices=[('Overcharging', 'Overcharging'), ('Refusal', 'Refusal to Convey'), ('No_Matrix', 'Missing Fare Matrix'), ('No_Discount', 'Denied 20% Discount'), ('Others', 'Other Violation (See Comments)')], max_length=20),
        ),
    ]
