# Generated by Django 6.0.2 on 2026-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_report_evidence_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_photo_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_photo',
            field=models.ImageField(blank=True, help_text='Photo upload of Student ID, Senior Citizen ID, or PWD ID', null=True, upload_to='id_photos/'),
        ),
    ]
