# Generated by Django 6.0.2 on 2026-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_userprofile_id_photo_url_userprofile_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_tip',
            field=models.BooleanField(default=False, help_text='True if extra paid was voluntary tip, False if overcharge'),
        ),
    ]
