# Generated by Django 6.0.2 on 2026-05-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_trip_is_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_tip',
        ),
    ]
