# Generated by Django 4.2.30 on 2026-06-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_trip_is_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_number',
            field=models.CharField(blank=True, help_text='Assigned Tricycle body number (for driver users)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='FCM push notification token', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farematrix',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
