# Generated by Django 4.2.30 on 2026-06-23 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_userprofile_body_number_userprofile_fcm_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='body_number',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_tricycle',
            field=models.ForeignKey(blank=True, help_text='The tricycle the driver is currently operating', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='dashboard.tricycle'),
        ),
        migrations.AlterField(
            model_name='farematrix',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Active', 'Active Ride'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase device token for push notifications', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Student', 'Student'), ('Senior', 'Senior Citizen'), ('PWD', 'Person with Disability'), ('Driver', 'Tricycle Driver')], default='Regular', max_length=15),
        ),
    ]
