# Generated by Django 4.2.30 on 2026-06-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_userprofile_body_number_trip_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Driver's last known latitude", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Driver's last known longitude", max_digits=9, null=True),
        ),
    ]
