# Generated by Django 4.2.30 on 2026-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_userprofile_current_lat_userprofile_current_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Student', 'Student'), ('Senior', 'Senior Citizen'), ('PWD', 'Person with Disability'), ('Pending Driver', 'Pending Driver Verification'), ('Driver', 'Tricycle Driver')], default='Regular', max_length=15),
        ),
    ]
