# Generated by Django 4.2.30 on 2026-07-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_photo',
            field=models.ImageField(blank=True, help_text='Photo upload of Student ID, Senior Citizen ID, PWD ID, Solo Parents ID, or Franchice/TODA ID for drivers', null=True, upload_to='id_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_discount_verified',
            field=models.BooleanField(default=False, help_text='Checked by Admin for verified approval'),
        ),
    ]
