# Generated by Django 4.2.30 on 2026-07-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_trip_dest_name_alter_userprofile_id_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='evidence_photo',
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_media',
            field=models.FileField(blank=True, null=True, upload_to='evidence_media/'),
        ),
    ]
