# Generated by Django 4.2.30 on 2026-07-13 08:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_report_evidence_photo_report_evidence_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='evidence_media',
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_photo',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='evidence_videos/'),
        ),
    ]
