"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
from django.urls import reverse_lazy
import os
from dotenv import load_dotenv
from datetime import timedelta # Moved up to group imports

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 🚀 CLEANED UP: Combined your ALLOWED_HOSTS here
ALLOWED_HOSTS = ['192.168.8.38', 'localhost', '127.0.0.1', "http://10.0.2.2:8000", '*']
CORS_ALLOW_ALL_ORIGINS = True

# Application definition
INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'dashboard',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# REST FRAMEWORK CONFIGURATION
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT SETTINGS
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

from django.templatetags.static import static

# ==========================================
# UNFOLD ADMIN DASHBOARD SETTINGS
# ==========================================
UNFOLD = {
    "SITE_TITLE": "Fair Admin",
    "SITE_HEADER": "FAIR ADMIN",
    "SITE_SYMBOL": "two_wheeler",
    "SITE_URL": None,
    "ENVIRONMENT": "Fair System MVP", 

    "DASHBOARD_CALLBACK": "dashboard.views.unfold_dashboard_callback",
    
    "LOGIN": {
        "image": lambda request: static("images/ac-bg.jpg"),
    },

    "COLORS": {
        "primary": {
            "50": "#fef2f2",
            "500": "#ef4444", 
            "600": "#dc2626",
            "700": "#C6121D",  
            "800": "#991b1b",
            "900": "#7f1d1d",
        },
    },
    
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Traffic Management",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Tricycle Registry",
                        "icon": "commute",
                        "link": reverse_lazy("admin:dashboard_tricycle_changelist"), 
                    },
                    {
                        "title": "Trip Records",
                        "icon": "route",
                        "link": reverse_lazy("admin:dashboard_trip_changelist"), 
                    },
                ],
            },
            {
                "title": "Audits & Compliance",
                "separator": True,
                "items": [
                    {
                        "title": "Dispute Reports", 
                        "icon": "report",
                        "link": reverse_lazy("admin:dashboard_report_changelist"), 
                    },
                    {
                        "title": "Commuter Profiles", 
                        "icon": "group",
                        "link": reverse_lazy("admin:dashboard_userprofile_changelist"),
                    },
                ],
            },
            {
                "title": "Regulatory Policies",
                "separator": True,
                "items": [
                    {
                        "title": "Fare Matrix (Ordinance)", 
                        "icon": "request_quote",
                        "link": reverse_lazy("admin:dashboard_farematrix_changelist"),
                    },
                ],
            },
            {
                "title": "Access Control",
                "separator": True,
                "items": [
                    {
                        "title": "Users", 
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        # 🚀 KEEP THIS: Only IT/Superadmins should manage accounts
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Logs", 
                        "icon": "history",
                        "link": reverse_lazy("admin:admin_logentry_changelist"), 
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}

# ==========================================
# EMAIL CONFIGURATION
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')
DEFAULT_FROM_EMAIL = f"Fair App Support <{os.getenv('EMAIL_USER')}>"