"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'dashboard',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST FRAMEWORK CONFIGURATION
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT SETTINGS (Optional but recommended for mobile apps)
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7), # Keeps users logged in for a week
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import os
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

from django.templatetags.static import static

UNFOLD = {
    "SITE_TITLE": "Fair Admin",
    "SITE_HEADER": "Angeles City LGU / TODA Portal",
    "SITE_SYMBOL": "two_wheeler",
    "SITE_URL": None,
    "ENVIRONMENT": "Fair System MVP", 
    
    "LOGIN": {
        "image": lambda request: static("images/ac-bg.jpg"),
    },

    "COLORS": {
        "primary": {
            "50": "#fef2f2",
            "500": "#ef4444", 
            "600": "#dc2626",
            "700": "#C6121D",  # Your main brand color
            "800": "#991b1b",
            "900": "#7f1d1d",
        },
    },
    
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Traffic Management",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Tricycle Registry",
                        "icon": "commute",
                        "link": reverse_lazy("admin:dashboard_tricycle_changelist"), 
                    },
                    {
                        "title": "Trip Records",
                        "icon": "route",
                        "link": reverse_lazy("admin:dashboard_trip_changelist"), 
                    },
                ],
            },
            {
                "title": "Audits & Compliance",
                "separator": True,
                "items": [
                    {
                        "title": "Dispute Reports", 
                        "icon": "report",
                        "link": reverse_lazy("admin:dashboard_report_changelist"), 
                    },
                    {
                        "title": "Passenger Profiles", 
                        "icon": "group",
                        "link": reverse_lazy("admin:dashboard_userprofile_changelist"),
                    },
                ],
            },
            {
                "title": "Regulatory Policies",
                "separator": True,
                "items": [
                    {
                        "title": "Fare Matrix (Ordinance)", 
                        "icon": "request_quote",
                        "link": reverse_lazy("admin:dashboard_farematrix_changelist"),
                    },
                ],
            },
        ],
    },
}

CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS = ['192.168.8.38', 'localhost', '127.0.0.1', '*']

# ==========================================
# EMAIL CONFIGURATION (Local Testing)
# ==========================================
# This prints the email to your terminal instead of actually sending it.
# When you go to production, you will change this to an SMTP backend (like SendGrid or AWS SES).
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Update these to pull from the .env file
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')
DEFAULT_FROM_EMAIL = f"Fair App Team <{os.getenv('EMAIL_USER')}>"